// ReSharper disable CheckNamespace
using Godot;

/// Generated by Forgotton Star Core Toolbox
/// 5/7/2024 7:33:42 AM
public partial class Registry
{
	public static class Audio
	{
		public static class SoundEffects
		{
			public static string Back001 = "res://assets/sfx/back_001.ogg";
			public static string Click1 = "res://assets/sfx/click1.ogg";
			public static string Click001 = "res://assets/sfx/click_001.ogg";
			public static string Close001 = "res://assets/sfx/close_001.ogg";
			public static string Confirmation001 = "res://assets/sfx/confirmation_001.ogg";
			public static string Drop001 = "res://assets/sfx/drop_001.ogg";
			public static string Error001 = "res://assets/sfx/error_001.ogg";
			public static string Glass001 = "res://assets/sfx/glass_001.ogg";
			public static string Glitch001 = "res://assets/sfx/glitch_001.ogg";
			public static string Maximize001 = "res://assets/sfx/maximize_001.ogg";
			public static string Minimize001 = "res://assets/sfx/minimize_001.ogg";
			public static string Mouseclick1 = "res://assets/sfx/mouseclick1.ogg";
			public static string Mouserelease1 = "res://assets/sfx/mouserelease1.ogg";
			public static string Open001 = "res://assets/sfx/open_001.ogg";
			public static string Pluck001 = "res://assets/sfx/pluck_001.ogg";
			public static string Question001 = "res://assets/sfx/question_001.ogg";
			public static string Rollover1 = "res://assets/sfx/rollover1.ogg";
			public static string Scratch001 = "res://assets/sfx/scratch_001.ogg";
			public static string Scroll001 = "res://assets/sfx/scroll_001.ogg";
			public static string Select001 = "res://assets/sfx/select_001.ogg";
			public static string Switch1 = "res://assets/sfx/switch1.ogg";
			public static string Switch001 = "res://assets/sfx/switch_001.ogg";
			public static string Tick001 = "res://assets/sfx/tick_001.ogg";
			public static string Toggle001 = "res://assets/sfx/toggle_001.ogg";
		}

		public static class Music
		{
			public static string RetroBeat = "res://assets/music/Retro Beat.ogg";
			public static string RetroComedy = "res://assets/music/Retro Comedy.ogg";
			public static string RetroMystic = "res://assets/music/Retro Mystic.ogg";
			public static string RetroPolka = "res://assets/music/Retro Polka.ogg";
			public static string RetroReggae = "res://assets/music/Retro Reggae.ogg";
		}
	}
}
